### ISSUE TITLE
Images missing in deals list (Android)

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#11]
# Location: 
https://www.swarmdev.city/my-profile/

# Expected behavior: 
Images not showing will  show.

# Actual behavior:
 Images do not show.

# Steps to reproduce the problem: 
1. Choose avatar to reveal my-profile. 2. Select "show deals". 3. Voila.

# screenshot/screencap: 
![rep list - 1 chrome](https://user-images.githubusercontent.com/30149603/39251497-6f88aed8-4871-11e8-8a12-bfbeeeadd585.jpg)

# Operating system / hardware: 
Oneplus 5 (A5000) OS: Oxygen 4.5.15, Android V7.1.1, Chrome V66.0.3359.126

**Comment by kikipluche** [comment]
this is not terminal, but boardwalk, this will be handled in the coming boardwalk epics
