### ISSUE TITLE
Prior transaction list does not show (Android)

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#12]
# Location: 
https://www.swarmdev.city/my-wallet/

# Expected behavior: 
Prior transaction list shows when I arrive on this page.

# Actual behavior: 
Prior transaction list does not show immediately. Once I do another transaction, then the prior transaction list shows.

# Steps to reproduce the problem:
 1.Restore account from backup JSON. 2. From https://www.swarmdev.city/hashtag-list/ select SWT balance, which send user to /my-wallet/. 3. Transaction list does not appear, even though profile has transacted in the past

# screenshot/screencap

# Operating system / hardware: 
One Plus 5 (A5000), OS Oxygen 4.5.15/Android V 7.1.1, Browser Chrome V 66.0.3359.126.
on mac as well.

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#713
