### ISSUE TITLE
Prior transaction list does not show (iMac)

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#13]
# Location: https://www.swarmdev.city/my-wallet/

# Expected behavior: Prior transaction list shows up.

# Actual behavior: After restoring from JSON backup, prior transaction list does not show up until the user does another transaction.

# Steps to reproduce the problem: 1. Restore user from JSON backup. 2. Select SWT balance on this page: https://www.swarmdev.city/hashtag-list/ 3. Arrive on https://www.swarmdev.city/my-wallet/

# screenshot/screencap: I missed the screen capture and couldn't reproduce.

# Operating system / hardware: iMac 27", OS Sierra/10.12.6, Browser - Chrome V65.0.3325.181

**Comment by kikipluche** [comment]
this is the same issue, i assume on all devices, will add this to issue 12
