### ISSUE TITLE
Images missing in deals list (iMac)

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#14]
# Location: https://www.swarmdev.city/my-profile/

# Expected behavior: Images not showing will show.

# Actual behavior: Images do not show.

# Steps to reproduce the problem: 1. Choose Avatar from https://www.swarmdev.city/hashtag-list/ to reveal /my-profile/. 2. Select "show deals". 3. Voila

# screenshot/screencap: 
![rep list imac chrome](https://user-images.githubusercontent.com/30149603/39257360-541c68ca-487f-11e8-880d-1ed4636dac8f.png)

# Operating system / hardware: iMac 27", OS Sierra 10.12.6, Chrom V65.0.3325.181

**Comment by kikipluche** [comment]
closing this issue, will be handled in boardwalk epics
