### ISSUE TITLE
SWT disappeared after restore from JSON

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#15]
# Location: 
https://www.swarmdev.city/hashtag-list/

# Expected behavior: 
User's SWT balance would remain after restoring from JSON.

# Actual behavior: 
User's SWT did not come back after restore from JSON. Here is a link to etherscan: https://rinkeby.etherscan.io/address/0xa7D3c0E6d55059c5B87149910eCD82DbE15747ED Wallet also shows 0 SWT.

# Steps to reproduce the problem: 
1. Restore User from backup JSON User had a 25 SWT balance. 2. Arrive on https://www.swarmdev.city/hashtag-list/. 3. User SWT balance is "0" and ETH balance has been reset to .1.

# screenshot/screencap: 
(captured after I sent SWT to this user, but it was zero until then, and you can see .1 ETH) 
![screen shot 2018-04-25 at 12 05 58 pm](https://user-images.githubusercontent.com/30149603/39258103-2265333c-4881-11e8-89ff-7407cc3671eb.png)

# Operating system / hardware:
 iMac 27", OS Sierra V10.12.6, Chrome V65.0.3325.181

**Comment by kikipluche** [comment]
i wasn't able to reproduce this on another device.
@matthewcarano are you able to reproduce it?

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#712
