### ISSUE TITLE
Avatar image did not return after restore from JSON

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#16]
# Location: 
https://www.swarmdev.city/hashtag-list/

# Expected behavior: 
Avatar will return after restore from JSON.

# Actual behavior:
 Avatar image didn't return until I selected the Avatar. Then I could see the picture in the resize box.

# Steps to reproduce the problem: 
1. Restore user from JSON. 2. Arrive on https://www.swarmdev.city/hashtag-list/. 3. Avatar doesn't restore. 4. Choose blank avatar section and avatar shows up in the resize box.

# screenshot/screencap: 
![screen shot 2018-04-25 at 12 17 20 pm](https://user-images.githubusercontent.com/30149603/39258709-9e752940-4882-11e8-94bc-7e10dd129a01.png)

# Operating system / hardware:
 iMac 27", OS Sierra V10.12.6, Chrome V65.0.3325.181

**Comment by kikipluche** [comment]
hey @matthewcarano i tried to reproduce the same error, but I can't. Can you reproduce it on the same device or other devices?

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#711
