### ISSUE TITLE
Choose restore account creates blank screen

### ISSUE THREAD

**Issue by matthewcarano** [swarmcity/SwarmCityPM#17]
# Location: 
https://www.swarmdev.city/restore-account/

# Expected behavior:
 Choose "restore account" and the /restore-account/ page populates with copy "How do you want to restore your account?" and 2 buttons (with a private key and upload an account file)

# Actual behavior: 
Choosing "restore account" on the /create-account/ page brings user to /restore-account/ page, but the page is blank.

# Steps to reproduce the problem: 
1. Choose "create account" which brings user to /create-account/ page. 2. Select "restore account" button which brings user to /restore-account/ page. 3. The /restore-account/page is blank.

# screenshot/screencap: 
![choose resotre and balck screen](https://user-images.githubusercontent.com/30149603/39259135-b16f7af4-4883-11e8-9119-26159bba25fd.png)

# Operating system / hardware:
 iMac 27", OS Sierra 10.12.6, Chrome V65.0.3325.181

**Comment by kikipluche** [comment]
this happens when the user does the restore account flow for the second time.
This is issue 592 in backlog
