### ISSUE TITLE
using private key as backup on all iOS devices

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityPM#2]
# Location
/make backup

# Expected behavior
When I am on an ipad iOS device  i can use the private key as backup

# Actual behavior
When i am on an ipad, i cannot use the checkmark to use private key as backup.

# Steps to reproduce the problem
On ipad make new account, make backup by copying private key.

# Operating system / hardware
ipad/iOS

**Comment by hershkoy** [comment]
@kikipluche this happens only on ipad, right?
I opened another bug that I have seen on the my-keys page. is this related to what you mean here? https://github.com/swarmcity/SwarmCitySite/issues/707

**Comment by kikipluche** [comment]
well, the other issue, i've seen happening too. we probably both created an issue, i'll check it out.
This one is about a wanted behaviour that isn't happening. So it needs to be changed so an ipad behaves as an iphone.

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#717
