### ISSUE TITLE
ITERATION: /my-wallet/

### ISSUE THREAD

**Issue by faffydee** [swarmcity/SwarmCityPM#23]
# Location
**route:** /my-wallet/
Based on behaviour of testers doing token transfers, live at Edcon, we created an iteration on page /my-wallet/. 

**Main problem to solve (OLD version):**
users would tap the 'show my keys' link, when the question was asked if they wanted tokens.

<img src="https://user-images.githubusercontent.com/24499354/39794475-80f12518-5318-11e8-9e48-3019c99153ea.png" width="700px">

**Solution:**

- [x] changing the location of the link
- [x] changing the copy of the link "show address on ethplorer"
- [x] changing size of buttons
- [x] changing order of buttons
- [x] changing the alignment of elements on mobile view

Also, we don't have to show the ETH-balance while on Rinkeby:
- [x] remove eth-balance
- [x] changing the font&color of dollar-value

LINK TO INVISION (inspect mode):
https://projects.invisionapp.com/d/main#/console/13838256/288387046/inspect

**Example of send-flow:**

<img src="https://user-images.githubusercontent.com/24499354/39794765-fe44ab88-5319-11e8-8e51-b3b670840fbc.png" width="700px">

**Comment by xardass** [comment]
I wrote the link to etherscan, as ethplorer didn't support rinkeby (?).
