### ISSUE TITLE
Modify ipfs add so it doesn't check if a base64 is sent

### ISSUE THREAD

**Issue by eduadiez** [swarmcity/SwarmCityPM#27]
- [x] Modification
- [x] Test modification
- [x] Merged
- [x] Deployed
- [x] Maintenance tasks on the server

**Comment by BvL13** [comment]
@eduadiez I already closed this, but could you still label what this is. Bug, Enhancement, Infrastructure etc. This will help me to judge on the storypoints. Thanks.

**Comment by eduadiez** [comment]
@BvL13 I have put it as an improvement, and associated with the Epic #7 that is the one that needed it. There was an inconsistency between what was defined in the Epic #4 and the #7, and this change was necessary.
