### ISSUE TITLE
S01E01 Epic 9: API returns the info of a concrete deal

### ISSUE THREAD

**Issue by eduadiez** [swarmcity/SwarmCityPM#30]
- [ ] Implement a function that returns a particular deal
- [ ] Testing

**Comment by BvL13** [comment]
Please move this to "Done & Merged" when it is done and in order to get the payment.
Thank you.

**Comment by eduadiez** [comment]
PR 127: https://github.com/swarmcity/SwarmCityAPI/pull/127
