### ISSUE TITLE
S01E01 Epic 8: Read the smartcontract events

### ISSUE THREAD

**Issue by eduadiez** [swarmcity/SwarmCityPM#37]
Create a job to read the smart contract events

**Comment by eduadiez** [comment]
This is how we finalized what the list should look like. (https://hackmd.io/nCj87b9_RvOhH9SeYw0aCw?both)

**Comment by BvL13** [comment]
Please move this to "Done & Merged" when it is done and in order to get the payment.
Thank you.

**Comment by eduadiez** [comment]
PR 127: https://github.com/swarmcity/SwarmCityAPI/pull/127
