### ISSUE TITLE
S01E01 Epic 8: Read the IPFS metadata and enrich the events

### ISSUE THREAD

**Issue by eduadiez** [swarmcity/SwarmCityPM#39]
Read the IPFS metadata and enrich the events

**Comment by eduadiez** [comment]
We found a problem with the IPFS library that causes the queries to not have a timeout which caused an API block.

Solving this meant an increase in the complexity of this Issue

**Comment by eduadiez** [comment]
It was necessary to make some improvement in the smartcontract and deploy it again.

**Comment by BvL13** [comment]
Please move this to "Done & Merged" when it is done and in order to get the payment.
Thank you.

**Comment by BvL13** [comment]
For future Issues try to stay with 8 Story Points max. If more time is needed break it down into two or more issues.
