### ISSUE TITLE
S01E01 Epic 8: API Testing

### ISSUE THREAD

**Issue by eduadiez** [swarmcity/SwarmCityPM#40]
Write the tests for the new functionalities implemented

**Comment by xardass** [comment]
@eduadiez I accidentally assigned you

**Comment by BvL13** [comment]
Please move this to "Done & Merged" when it is done and in order to get the payment.
Thank you.

**Comment by eduadiez** [comment]
PR 127: https://github.com/swarmcity/SwarmCityAPI/pull/127
